/* Flashcard-data för Fysiologi Gy25 */
const ALL_CARDS = [
  // ─── MATSPJÄLKNING ──────────────────────────────────────────────────────────
  {cat:'mat', term:'Autotrof', def:'Organism som kan tillverka sin egen näring, t.ex. via fotosyntes. Växter och alger är autotrofer – de behöver inte äta för att få energi.'},
  {cat:'mat', term:'Heterotrof', def:'Organism som måste äta organiska ämnen för att få energi och byggmaterial. Människor och djur är heterotrofer.'},
  {cat:'mat', term:'Herbivorer', def:'Växtätande djur. Har långa mag-tarmkanaler och specialiserade anpassningar för att bryta ned cellulosa.'},
  {cat:'mat', term:'Karnivorer', def:'Köttätande djur. Har kortare mag-tarmkanaler eftersom animalisk föda bryts ned snabbare och enklare.'},
  {cat:'mat', term:'Omnivorer', def:'Allätande djur som äter både växter och kött. Människan är ett omnivorer med ett mellanting av matspjälkningssystem.'},
  {cat:'mat', term:'Kolhydrater', def:'Organiska molekyler uppbyggda av kol, väte och syre. Kroppens primära energikälla; bryts ned till monosackarider (framförallt glukos) som förbränns till ATP.'},
  {cat:'mat', term:'Fett (glycerol & fettsyra)', def:'Lipid uppbyggd av en glycerolmolekyl med upp till tre fettsyror. Kroppens viktigaste energireserv och byggsten i cellmembran. Innehåller ca dubbelt så mycket energi per gram som kolhydrater.'},
  {cat:'mat', term:'Protein', def:'Stor molekyl uppbyggd av aminosyror. Fungerar som enzymer, strukturproteiner, transportmolekyler och hormoner. Kan inte lagras – överskott bryts ned i levern.'},
  {cat:'mat', term:'Vitamin (fettlösliga & vattenlösliga)', def:'Organiska molekyler kroppen behöver i liten mängd. Fettlösliga (A, D, E, K) lagras i fettvävnad. Vattenlösliga (B, C) lagras inte utan måste tillföras dagligen.'},
  {cat:'mat', term:'Mineraler (oorganiska joner)', def:'Oorganiska ämnen som kalcium, järn och natrium. Byggstenar och reglerar biologiska processer, t.ex. muskelkontraktion och nervimpulser.'},
  {cat:'mat', term:'Tunntarm', def:'5–7 meter lång del av matspjälkningskanalen där merparten av kemisk nedbrytning och absorption av näring sker. Övre delen kallas tolvfingertarmen.'},
  {cat:'mat', term:'Tjocktarm', def:'Absorberar vatten och salter från kvarvarande mag-tarminnehåll. Bestämmer avföringens konsistens och hyser normalfloran.'},
  {cat:'mat', term:'Ändtarm', def:'Tillfälligt förråd för avföring. Avföring ansamlas tills mekanoreceptorer signalerar toalettbehov. Kontrolleras av inre (ofrivillig) och yttre (frivillig) sfinkter.'},
  {cat:'mat', term:'Matstrupe', def:'Rör som förbinder svalget med magsäcken. Transporterar mat via peristaltiska rörelser; tyngdkraften är inte avgörande.'},
  {cat:'mat', term:'Saltsyra', def:'HCl. Produceras i magsäcksväggen och sänker pH till ~2. Dödar bakterier, denaturerar proteiner och aktiverar pepsinogen till pepsin.'},
  {cat:'mat', term:'Denaturera', def:'När ett proteins tredimensionella struktur bryts ned (utan att peptidkedjorna klyvs). I magsäcken gör saltsyran detta med proteiner, vilket gör det lättare för enzymer att bryta ned dem.'},
  {cat:'mat', term:'Enzym', def:'Biologisk katalysator (vanligen protein) som snabbar upp kemiska reaktioner utan att förbrukas. Specifika – varje enzym passar bara en typ av substrat.'},
  {cat:'mat', term:'Munhålan', def:'Matspjälkningens startpunkt. Tänder gör mekanisk nedbrytning; saliv med amylas gör kemisk nedbrytning av stärkelse.'},
  {cat:'mat', term:'Saliv & spottkörtel', def:'Spottkörtelarna producerar saliv. Saliv innehåller vatten, slem (smörjer), och enzymet amylas som startar nedbrytningen av stärkelse.'},
  {cat:'mat', term:'Lever', def:'Multiuppgiftsorgan: bryter ned gifter, lagrar glykogen, producerar galla (gallsalter och bilirubin), bildar urinämne från aminosyranedbrytning.'},
  {cat:'mat', term:'Gallblåsan', def:'Reservoar under levern där gallan koncentreras. Tömmer sig via gallgångar till tolvfingertarmen när fet mat anländer.'},
  {cat:'mat', term:'Bukspottkörteln', def:'Producerar bukspott (alkaliskt, innehåller amylas, lipas, proteaser, nukleaser) och hormonerna insulin och glukagon.'},
  {cat:'mat', term:'Blindtarmen', def:'Caecum. Hos växtätare viktig för cellulosanedbrytning via bakterier. Hos människan trolig roll i immunförsvaret. Köttätare har mycket liten blindtarm.'},
  {cat:'mat', term:'Amylas', def:'Enzym som bryter ned stärkelse (polysackarider) till kortare sockerarter. Finns i saliven och i bukspottet.'},
  {cat:'mat', term:'Villi (tarmludd)', def:'Fingerformade utskott på tunntarmens innersida. Ökar absorptionsytan dramatiskt. Varje villus täckt av mikrovilli (ger total yta ~200 m²).'},
  {cat:'mat', term:'Pepsin', def:'Aktivt proteolytiskt enzym i magsäcken. Bryter ned proteiner till kortare peptidkedjor. Aktiveras från pepsinogen av saltsyra.'},
  {cat:'mat', term:'Pepsinogen', def:'Inaktivt proenzym utsöndrat av huvudcellerna. Omvandlas till aktivt pepsin i magsäckens sura miljö. Inaktiv form skyddar väggen från självnedbrytning.'},
  {cat:'mat', term:'Galla', def:'Produceras i levern, lagras i gallblåsan. Innehåller gallsalter (emulgerar fett), bilirubin och hormoner. Höjer pH i tolvfingertarmen.'},
  {cat:'mat', term:'Gallsalter', def:'Biologiska "tvättmedel" i gallan. Finfördelar stora fettdroppar till många små (emulgering), vilket ökar ytan för lipasets verkan. Är inte enzymer.'},
  {cat:'mat', term:'Tolvfingertarmen', def:'Duodenum – tunntarmens översta ~25 cm. Navet för kemisk nedbrytning; tar emot galla från gallblåsan och bukspott från bukspottkörteln.'},
  {cat:'mat', term:'Lipas', def:'Enzym som bryter ned fetter (triglycerider) till fettsyror och glycerol. Produceras av bukspottkörteln; gallsalter krävs för effektiv verkan.'},
  {cat:'mat', term:'Proteaser', def:'Grupp av enzymer som bryter ned proteiner till korta peptider och aminosyror. Inkluderar pepsin (magsäck) och bukspottets trypsin/chymotrypsin.'},
  {cat:'mat', term:'Bukspott', def:'Alkalisk vätska från bukspottkörteln. Neutraliserar det sura innehållet från magsäcken och tillför enzymer (amylas, lipas, proteaser, nukleaser).'},
  {cat:'mat', term:'Mikrovilli', def:'Extremt täta, finförgrenade utskott på varje villi-cell. Bildar "borstbrämet". Ökar tunntarmens totala absorptionsyta till ~200 m².'},
  {cat:'mat', term:'Lymfkärl', def:'I tunntarmens villi transporterar lymfkärlen fetter (kylomikroner) som är för stora för blodkapillärerna. Lymfan återansluts till blodet via hålvenen.'},
  {cat:'mat', term:'Peristaltik (peristaltisk rörelse)', def:'Koordinerad sammandragning och avslappning av glatt muskulatur i matspjälkningskanalen. Transporterar maten framåt oberoende av tyngdkraften.'},
  {cat:'mat', term:'Blandningsrörelser', def:'Rörelser i magsäck och tunntarm som knådar och blandar innehållet med enzymer, utan att föra det framåt. Ökar kontaktytan.'},
  {cat:'mat', term:'Helicobacter pylori', def:'Bakterie som orsakar magsår. Producerar ammoniak (basiskt) och gifter som förstör epitelcellerna i magsäcken, och låter saltsyran tränga igenom.'},
  {cat:'mat', term:'Bilirubin', def:'Gulbrunt nedbrytningsprodukt från gamla röda blodkroppar. Ingår i gallan och ger avföring och galla sin färg.'},
  {cat:'mat', term:'Sfinktrar', def:'Ringformade muskler som reglerar öppningar i matspjälkningskanalen, t.ex. vid pylorus (magsäck→tolvfingertarm) och ändtarmen. Kontrollerar flödet.'},
  {cat:'mat', term:'Fria radikaler', def:'Molekyler/atomer med ett eller flera oparade elektroner. Extremt reaktiva – "stjäl" elektroner från DNA, proteiner och membraner. Bildas vid ämnesomsättning och immunförsvar.'},
  {cat:'mat', term:'Antioxidanter', def:'Ämnen som neutraliserar fria radikaler genom att avge en elektron utan att själva destabiliseras. T.ex. vitamin C, E och betakaroten.'},
  {cat:'mat', term:'Gomsegel', def:'Mjuka gommen bak i munhålan. Stängs vid sväljning för att hindra mat från att hamna i näsan.'},
  {cat:'mat', term:'Glattmuskulatur', def:'Ofrivillig muskulatur i matspjälkningskanalens väggar. Styrs av autonoma nervsystemet. Utför peristaltik och blandningsrörelser.'},
  {cat:'mat', term:'Epitelceller', def:'Celler som bildar det skyddande innerlagret i matspjälkningskanalen. I magsäcken producerar de saltsyra, pepsinogen och slem.'},
  {cat:'mat', term:'Struplock', def:'Epiglottis – broskplatta som fälls ner vid sväljning och täcker luftstrupens öppning, så att mat inte hamnar i lungorna.'},
  {cat:'mat', term:'Magsäck', def:'Töjbar muskelisk påse (~2 liter) där mat bearbetas 2–6 timmar. Producerar magsaft (HCl, pepsinogen, slem) och gör blandningsrörelser.'},
  {cat:'mat', term:'Magsaft', def:'Vätska producerad av magsäcken. Innehåller saltsyra (HCl), pepsinogen och slem. pH ≈ 2.'},
  {cat:'mat', term:'Magsår', def:'Sår på magsäckens eller tunntarmens slemhinna. Orsakas av H. pylori-infektion eller när saltsyra/pepsin förstör epitelcellerna snabbare än de läker.'},
  {cat:'mat', term:'Metabolism', def:'Alla biokemiska reaktioner i kroppen. Delas i katabola (nedbrytande, t.ex. cellandning) och anabola (uppbyggande, t.ex. proteinsyntes) reaktioner.'},
  {cat:'mat', term:'Normalflora (symbiotiska mikroorganismer)', def:'Bakterier och andra mikroorganismer i tarmarna som lever i mutualistisk symbios med kroppen. Hjälper bryta ned fibrer, producerar vitaminer (t.ex. K) och stärker immunförsvaret.'},
  {cat:'mat', term:'Glykogen', def:'Lagringsform av glukos i lever och muskler. Polysackarid som snabbt kan brytas ned till glukos vid energibehov.'},
  {cat:'mat', term:'Idissla', def:'Idisslare (t.ex. kor) hämtar upp och tuggar om födan en extra gång. Mikroorganismer i vommen fermenterar cellulosa.'},

  // ─── RESPIRATION ────────────────────────────────────────────────────────────
  {cat:'resp', term:'Diffusion', def:'Spontan rörelse av molekyler från hög koncentration till låg koncentration längs koncentrationsgradienten. Drivkraften för gasutbyte i lungor och vävnader.'},
  {cat:'resp', term:'Koncentrationsgradient', def:'Skillnaden i koncentration av ett ämne mellan två områden. Ju större gradient, desto snabbare och effektivare diffusion.'},
  {cat:'resp', term:'Gasutbyte', def:'Processen där syre tas upp och koldioxid avges, antingen i lungorna (från luft till blod) eller i vävnaderna (från blod till celler).'},
  {cat:'resp', term:'Gälar (yttre och inre)', def:'Vattenanpassat andningsorgan hos fiskar och grodlarver. Yttre gälar sitter på kroppen (oskyddade), inre gälar i skyddad gälkammare med enkelriktat vattenflöde.'},
  {cat:'resp', term:'Motströmningsprincipen', def:'Blod och vatten flödar i motsatta riktningar i fiskgälar. Upprätthåller ständig koncentrationsgradient längs hela gälen → maximalt effektivt gasutbyte.'},
  {cat:'resp', term:'Luftstrupe', def:'Trakea. ~10 cm lång, hålls öppen av broskringar. Slemhinna och cilier fångar och transporterar partiklar bort från lungorna.'},
  {cat:'resp', term:'Bronker', def:'Två grenar av luftstrupen (en per lunga). Samma uppbyggnad som luftstrupen med broskringar, slem och cilier.'},
  {cat:'resp', term:'Bronkioler', def:'Finaste förgreningarna av bronkerna. Leder luften till alveolerna. Saknar brosk – kan vidgas/snävas av glatt muskulatur.'},
  {cat:'resp', term:'Alveoler', def:'Lungblåsor – tunna säckar (ett celllager) i änden av bronkiolerna. Omgivna av kapillärer. Total yta ~70–140 m². Platsen för gasutbytet.'},
  {cat:'resp', term:'Cilier/flimmerhår', def:'Hårfina utskott på slemhinnan i luftvägarna. Transporterar slem (med fångade partiklar/bakterier) uppåt mot svalget. Förlamat av nikotin.'},
  {cat:'resp', term:'Diafragma', def:'Mellangärdet – platt muskel under lungorna. Kontraherar vid inandning (sänks → bröstkorgsvolym ökar → undertryck). Slappnar av vid utandning.'},
  {cat:'resp', term:'Lunglober', def:'Lungorna är indelade i lober: höger lunga har 3, vänster 2 (pga hjärtat). Varje lob försörjs av en egen bronk.'},
  {cat:'resp', term:'Andningsmekanismen', def:'Tryckstyrd process. Inandning: diafragma sänks → volym ökar → tryck sjunker → luft strömmar in. Utandning (passiv): diafragma välver upp → volym minskar → luft pressas ut.'},
  {cat:'resp', term:'Vitalkapacitet', def:'Maximal luftmängd som kan andas ut efter en maximal inandning. Mäter lungkapaciteten. Minskar vid KOL och emfysem.'},
  {cat:'resp', term:'Residualvolym (Restvolym)', def:'~1,2 liter luft som alltid finns kvar i lungorna och inte kan andas ut. Håller alveolerna öppna och förhindrar att lungorna kollapsar.'},
  {cat:'resp', term:'Tidalvolym', def:'Luftmängden vid ett normalt andetag i vila, ca 500 ml. Av dessa når bara ~350 ml alveolerna (resten stannar i dead-space).'},
  {cat:'resp', term:'Andningscentrum', def:'Nervcentrum i hjärnstammen som styr andningsrytmen. Känsligt för koldioxidhalt och pH i blodet – hög CO₂/lågt pH ökar andningsfrekvensen.'},
  {cat:'resp', term:'Kapillärer (lungor)', def:'Minsta blodkärlen med vägg av ett enda celllager. Omger alveolerna tätt – kort diffusionsväg (<1 µm) möjliggör effektivt gasutbyte.'},
  {cat:'resp', term:'Röda blodkroppar', def:'Erytrocyter. Packade med hemoglobin, saknar cellkärna. Transporterar syre (och en del CO₂). Lever ~120 dagar.'},
  {cat:'resp', term:'Hemoglobin', def:'Järnhaltigt protein i röda blodkroppar. Binder 4 syremolekyler per molekyl. Binder O₂ i lungorna, släpper det i aktiv vävnad (vid lågt pH/hög CO₂).'},
  {cat:'resp', term:'Koldioxid', def:'CO₂. Avfallsprodukt från cellandningen. Transporteras i blodet som vätekarbonat (75–80%), bundet till Hb (10–20%) eller löst i plasma (5–10%).'},
  {cat:'resp', term:'Kolsyra', def:'H₂CO₃. Bildas när CO₂ reagerar med vatten i blodet: CO₂ + H₂O ⇌ H₂CO₃. Dissocierar till vätekarbonat och vätejoner, vilket sänker blodets pH.'},
  {cat:'resp', term:'Vätekarbonat', def:'HCO₃⁻. Transportform för 75–80% av kroppens koldioxid i blodet. Bildas när kolsyra dissocierar. I lungorna sker processen baklänges.'},
  {cat:'resp', term:'pH (blod)', def:'Mått på surhet/basiskhet. Blodets normala pH är ~7,4. Sjunker (surare) vid hög CO₂-ansamling → signalerar ökat andningsbehov.'},
  {cat:'resp', term:'Syrgas', def:'O₂. Tas upp i alveolerna via diffusion och transporteras bundet till hemoglobin. Förbrukas i mitokondrierna vid cellandning.'},
  {cat:'resp', term:'Kolmonoxid', def:'CO. Färglös, luktlös gas vid ofullständig förbränning. Binder till hemoglobin ~200× starkare än O₂ → blockerar syretransport → kvävning trots tillgängligt syre.'},
  {cat:'resp', term:'Trakeér', def:'Insekters luftrörsystem. Grenat rörsystem av luftrör (trakeoler) som leder luft direkt till vävnaderna utan att gå via blodet. Effektivt men storleksbegränsande.'},
  {cat:'resp', term:'Luftsäckar (fåglar)', def:'Hos fåglar: säckar kopplade till lungorna som styr ett enkelriktat luftflöde genom parabronkiala rör vid både in- och utandning. Ger det effektivaste lundsystemet bland ryggradsdjur.'},
  {cat:'resp', term:'Lunginflammation', def:'Infektion (bakteriell/viral) i alveolerna. Alveolerna fylls med vätska/pus → minskat gasutbyte → andningssvårigheter.'},
  {cat:'resp', term:'Emfysem', def:'Förstöring av alveolernas väggar. Minskar gasutbytesytan dramatiskt → kronisk andnöd. Vanlig följd av långvarig rökning.'},
  {cat:'resp', term:'KOL', def:'Kroniskt obstruktiv lungsjukdom. Kombination av luftvägsinflammation och emfysem. Ger försämrat luftflöde, andfåddhet, hosta. Orsakas nästan alltid av rökning.'},
  {cat:'resp', term:'Dead-space', def:'Volymen luft (~150 ml) i luftvägar som deltar i andningen men inte når alveolerna och inte bidrar till gasutbyte. Av 500 ml tidalvolym når ~350 ml faktiskt alveolerna.'},

  // ─── CIRKULATION ────────────────────────────────────────────────────────────
  {cat:'cirk', term:'Artärer (lung-/kropp-)', def:'Leder blod från hjärtat. Tjocka, elastiska väggar tål högt tryck. Lungartären = syrefattigt blod till lungorna. Kroppens artärer = syrerikt blod till organen.'},
  {cat:'cirk', term:'Vener (lung-/kropp-)', def:'Leder blod till hjärtat. Tunnare väggar, lägre tryck, innehåller venklaffar. Lungven = syrerikt blod till hjärtat. Kroppsvener = syrefattigt blod till höger förmak.'},
  {cat:'cirk', term:'Kapillärer', def:'Minsta blodkärlen (ett cellager tjocka). Enda platsen för verkligt ämnesutbyte – syre, näring och koldioxid diffunderar/filtreras mellan blod och vävnader.'},
  {cat:'cirk', term:'Kranskärl', def:'Artärer som löper längs hjärtats yta och försörjer hjärtmuskeln med syre och näring. Om de täpps till uppstår hjärtinfarkt.'},
  {cat:'cirk', term:'Blodtryck', def:'Det tryck blodet utövar på kärlväggarna. Anges som systoliskt/diastoliskt (t.ex. 120/80 mmHg). Höjs av hjärtkontraktion, sänks när hjärtat vilar.'},
  {cat:'cirk', term:'Systoliskt / Diastoliskt tryck', def:'Systoliskt (~120 mmHg): trycket när hjärtats kamrar kontraherar. Diastoliskt (~80 mmHg): trycket när hjärtat vilar och kamrarna fylls.'},
  {cat:'cirk', term:'Hålven', def:'Stora vener (övre och nedre hålvenen) som samlar upp syrefattigt blod från hela kroppen och leder det till hjärtats högra förmak.'},
  {cat:'cirk', term:'Aorta', def:'Kroppens största artär (diameter ~2,5 cm). Utgår från vänster kammare. Kranskärlen löper härifrån. Elastiska väggar buffrar tryckstötar.'},
  {cat:'cirk', term:'Lilla kretsloppet', def:'Lungkretsloppet. Höger kammare → lungartär → lungor (syresättning/CO₂-avgång) → lungven → vänster förmak.'},
  {cat:'cirk', term:'Stora kretsloppet', def:'Kroppskretsloppet. Vänster kammare → aorta → artärer → kapillärer (vävnadsutbyte) → vener → hålvener → höger förmak.'},
  {cat:'cirk', term:'Segelklaff', def:'Atrioventrikulärklaff mellan förmak och kammare. Stängs under systole för att hindra blod från att flöda bakåt från kammare till förmak.'},
  {cat:'cirk', term:'Fickklaff', def:'Halvmåneklaff vid utloppet från kamrarna (aorta och lungartären). Öppnas under systole, stängs under diastole – förhindrar bakflöde från artär till kammare.'},
  {cat:'cirk', term:'Slagvolym', def:'Blodmängden som pumpas ut per hjärtslag, ~70 ml i vila. Ökar vid träning.'},
  {cat:'cirk', term:'Minutvolym', def:'Totalt pumpat blod per minut. Slagvolym × pulsfrekvens ≈ 70 ml × 70 slag/min ≈ 5 l/min i vila. Kan öka till ~25 l/min vid hårt arbete.'},
  {cat:'cirk', term:'Sfinktrar (kapillärer)', def:'Ringmuskler vid kapillärernas ingång. Reglerar blodflödet till enskilda kapillärnät beroende på vävnadens aktivitet.'},
  {cat:'cirk', term:'Ämnesutbyte i kapillärerna', def:'Sker via diffusion och filtration. Det hydrostatiska trycket driver ut vätska vid ingångssidan; osmotiskt tryck (blodproteiner) suger tillbaka ~99% vid utgångssidan.'},
  {cat:'cirk', term:'Blodproteiner', def:'T.ex. albumin i blodplasman. Skapar det osmotiska trycket som suger tillbaka vävnadsvätska till kapillärerna. Låga nivåer → ödem.'},
  {cat:'cirk', term:'Ödem', def:'Svullnad orsakad av ansamling av vävnadsvätska. Uppstår vid lågt blodprotein, högt blodtryck eller blockerade lymfkärl – balansen mellan filtration och reabsorption rubbas.'},
  {cat:'cirk', term:'Hydrostatiska trycket', def:'Det tryck blodet utövar på kapillärväggarna. Högt vid ingångssidan → driver filtration av vätska ut i vävnaden.'},
  {cat:'cirk', term:'Osmotiska trycket (vattenpotential)', def:'Trycket som uppstår pga lösta molekylers (proteiners) koncentration i blodet. Suger tillbaka vätska från vävnaden till kapillärerna vid utgångssidan.'},
  {cat:'cirk', term:'Homeostas', def:'Kroppens förmåga att upprätthålla ett stabilt inre tillstånd (t.ex. temperatur, pH, blodsocker) trots yttre förändringar. Cirkulationssystemet är centralt.'},
  {cat:'cirk', term:'Endoterma (jämnvarma djur)', def:'Däggdjur och fåglar. Producerar kroppsvärme internt via hög ämnesomsättning. Kräver effektivt cirkulationssystem och fyrrummigt hjärta.'},
  {cat:'cirk', term:'Ektoterma (växelvarma djur)', def:'Fiskar, reptiler, amfibier. Beroende av omgivningstemperaturen. Lägre metabolismkrav – klarar sig med enkelt eller trerummigt hjärta.'},
  {cat:'cirk', term:'Blodplasma', def:'55% av blodet. Innehåller ~90% vatten, proteiner (albumin, fibrinogen), näring, hormoner och avfallsprodukter.'},
  {cat:'cirk', term:'Fibrinogen', def:'Plasmaprotein som vid skada omvandlas till fibrin – klibbiga trådar som bildar ett koagel och tätar såret.'},
  {cat:'cirk', term:'Fibrin', def:'Aktiverad form av fibrinogen. Bildar ett nät av trådar som fångar blodkroppar och tätar skadade blodkärl vid koagulering.'},
  {cat:'cirk', term:'Röda blodkroppar (erytrocyter)', def:'Bär hemoglobin för syretransport. Saknar cellkärna och organeller – maximerar plats för Hb. Bikonkav form ökar yta. Lever ~120 dagar.'},
  {cat:'cirk', term:'Vita blodkroppar (leukocyter)', def:'Immunförsvarets celler. Identifierar och bekämpar patogener, producerar antikroppar. Finns i lymfknutor och blod.'},
  {cat:'cirk', term:'Blodplättar (trombocyter)', def:'Cellfragment viktiga för blodkoagulering. Aktiveras vid kärlskada och bildar tillsammans med fibrin ett tätnande koagel.'},
  {cat:'cirk', term:'Enkelt och dubbelt kretslopp', def:'Enkelt (fiskar): blodet passerar hjärtat en gång per varv – lägre tryck. Dubbelt (fåglar/däggdjur): blodet passerar hjärtat två gånger (lilla + stora kretsloppet) – högre tryck.'},
  {cat:'cirk', term:'Öppet och slutet blodkärlssystem', def:'Öppet: blodet lämnar kärlen och blandas med vävnadsvätska (insekter/snäckor). Slutet: blodet stannar inuti kärlen hela tiden (ringmaskar, bläckfiskar, ryggradsdjur).'},
  {cat:'cirk', term:'Två-, tre-, fyrrummigt hjärta', def:'Tvårummigt (fiskar): ett förmak + en kammare. Trerummigt (groddjur/kräldjur): viss blandning av blod. Fyrrummigt (fåglar/däggdjur): fullständig separation – effektivast.'},
  {cat:'cirk', term:'Hjärtcykel', def:'Ett komplett hjärtslag med två faser: systole (kamrarnas kontraktion, blod pumpas ut) och diastole (kamrarna slappnar av och fylls).'},
  {cat:'cirk', term:'Lymfa', def:'Vätska i lymfkärlen. Uppstår från vävnadsvätska (1% av filtrerat plasma som inte återtas av kapillärerna). Återförs till blodet via hålvenen.'},
  {cat:'cirk', term:'Lymfkärlen', def:'Transporterar lymfa och fetter (kylomikroner) från tarmarna. Liknar vener: tunna väggar och klaffar. Drivs av skelettmuskelrörelser.'},
  {cat:'cirk', term:'Lymfknutar', def:'Filterstationer längs lymfkärlen fyllda med vita blodkroppar. Filtrerar patogener ur lymfan. Svullnar vid infektion.'},
  {cat:'cirk', term:'Vänster/höger kammarvägg', def:'Vänster kammares vägg är tjockare – pumpar blod runt hela kroppen (högt tryck). Höger kammares vägg är tunnare – pumpar bara till lungorna (kortare sträcka).'},
  {cat:'cirk', term:'Hemoglobin (cirkulation)', def:'Järnhaltigt protein i röda blodkroppar. Binder O₂ i lungorna (hög O₂, högt pH) och släpper det i aktiva vävnader (lågt pH, hög CO₂). Ger blod dess röda färg.'},
  {cat:'cirk', term:'Bilirubin (cirkulation)', def:'Nedbrytningsprodukt från gamla röda blodkroppar (hemoglobin). Ingår i gallan och ger avföringen dess gulbruna färg. Höga nivåer → gulsot.'},
];
